// GENERATED by scripts/gen_protocol.py from protocol/schema.json.
// Do not edit. The protocol ratchet regenerates and diffs this file, so an
// edit here fails the build rather than drifting silently (S4.4).


export const PROTOCOL_VERSION = "1.0.0";

export type Mode = "plan" | "debug" | "agent";
export type TurnOutcome = "tool_call_executed" | "tool_call_refused" | "text_only" | "length_capped" | "cancelled" | "backend_error";
export type ToolStatus = "ok" | "tool_error" | "denied" | "timeout" | "refused" | "cancelled";

export interface SamplingSettings {
  temperature: number;
  top_p: number;
  top_k: number;
  min_p: number;
  repetition_penalty: number;
  seed: number;
}

export interface RunSettings {
  model_dir: string;
  workspace_root: string;
  mode: Mode;
  sampling: SamplingSettings;
  max_iterations: number;
  wall_clock_seconds: number;
  sandbox_tier: number;
  require_approval: boolean;
  context_budget_tokens: number;
}

export interface CapabilityChips {
  writes_outside_workspace: boolean;
  reads_outside_workspace: boolean;
  destroys_data: boolean;
  rewrites_vcs_history: boolean;
  network_access: boolean;
  spawns_unbounded_process: boolean;
  signals_foreign_process: boolean;
  escalates_privileges: boolean;
  parse_status: string;
}

export interface PerfSample {
  ttft_ms: number;
  prefill_tok_per_s: number;
  decode_tok_per_s: number;
  context_used: number;
  context_max: number;
  tokens_generated: number;
}

export interface StartParams {
  mission: string;
  settings: RunSettings;
}
export interface StartResult {
  run_id: string;
}

export interface CancelParams {
  run_id: string;
}
export interface CancelResult {
  accepted: boolean;
}

export interface ApproveParams {
  request_id: string;
  approved: boolean;
}
export interface ApproveResult {
  accepted: boolean;
}

export interface ShutdownParams {
}
export interface ShutdownResult {
  ok: boolean;
}

export interface TokenNotification {
  run_id: string;
  text: string;
  channel: string;
}

export interface TurnNotification {
  run_id: string;
  outcome: TurnOutcome;
  tool_name: string;
  tool_args: string;
  tool_status: ToolStatus;
  summary: string;
  duration_ms: number;
}

export interface ChecklistNotification {
  run_id: string;
  items_json: string;
}

export interface VerificationNotification {
  run_id: string;
  contract: string;
  passed: boolean;
  falsifiable: boolean;
  detail: string;
}

export interface ApprovalRequestNotification {
  request_id: string;
  run_id: string;
  tool_name: string;
  preview: string;
  risk: number;
  capabilities: CapabilityChips;
}

export interface EditNotification {
  run_id: string;
  path: string;
  new_content: string;
}

export interface PerfNotification {
  run_id: string;
  sample: PerfSample;
}

export interface RunEndNotification {
  run_id: string;
  termination_reason: string;
  iterations: number;
  completed: boolean;
}

export const METHODS = [
  "lmp/start",
  "lmp/cancel",
  "lmp/approve",
  "lmp/shutdown",
  "lmp/token",
  "lmp/turn",
  "lmp/checklist",
  "lmp/verification",
  "lmp/approval_request",
  "lmp/edit",
  "lmp/perf",
  "lmp/run_end",
] as const;
