// GENERATED by scripts/gen_protocol.py from protocol/schema.json.
// Do not edit. The protocol ratchet regenerates and diffs this file, so an
// edit here fails the build rather than drifting silently (S4.4).

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace lmp::protocol {

inline constexpr const char* kProtocolVersion = "1.0.0";

// Value serializers. String escaping is delegated to the platform layer so the
// protocol and the event log cannot disagree about what a JSON string is.
void append_value(std::string& out, const std::string& v);
inline void append_value(std::string& out, std::int64_t v) { out += std::to_string(v); }
inline void append_value(std::string& out, double v) { out += std::to_string(v); }
inline void append_value(std::string& out, bool v) { out += v ? "true" : "false"; }

// Mode: crosses the wire as one of these literals.
namespace mode_values {
inline constexpr const char* kPlan = "plan";
inline constexpr const char* kDebug = "debug";
inline constexpr const char* kAgent = "agent";
}

// TurnOutcome: crosses the wire as one of these literals.
namespace turnoutcome_values {
inline constexpr const char* kToolCallExecuted = "tool_call_executed";
inline constexpr const char* kToolCallRefused = "tool_call_refused";
inline constexpr const char* kTextOnly = "text_only";
inline constexpr const char* kLengthCapped = "length_capped";
inline constexpr const char* kCancelled = "cancelled";
inline constexpr const char* kBackendError = "backend_error";
}

// ToolStatus: crosses the wire as one of these literals.
namespace toolstatus_values {
inline constexpr const char* kOk = "ok";
inline constexpr const char* kToolError = "tool_error";
inline constexpr const char* kDenied = "denied";
inline constexpr const char* kTimeout = "timeout";
inline constexpr const char* kRefused = "refused";
inline constexpr const char* kCancelled = "cancelled";
}

struct SamplingSettings {
    double temperature = 0.0;
    double top_p = 0.0;
    std::int64_t top_k = 0;
    double min_p = 0.0;
    double repetition_penalty = 0.0;
    std::int64_t seed = 0;
};
inline void append_value(std::string& out, const SamplingSettings& v) {
    out += "{";
    out += "\"temperature\":";
    append_value(out, v.temperature);
    out += ",";
    out += "\"top_p\":";
    append_value(out, v.top_p);
    out += ",";
    out += "\"top_k\":";
    append_value(out, v.top_k);
    out += ",";
    out += "\"min_p\":";
    append_value(out, v.min_p);
    out += ",";
    out += "\"repetition_penalty\":";
    append_value(out, v.repetition_penalty);
    out += ",";
    out += "\"seed\":";
    append_value(out, v.seed);
    out += "}";
}

struct RunSettings {
    std::string model_dir;
    std::string workspace_root;
    std::string mode;
    SamplingSettings sampling;
    std::int64_t max_iterations = 0;
    std::int64_t wall_clock_seconds = 0;
    std::int64_t sandbox_tier = 0;
    bool auto_approve_exec = false;
    bool auto_approve_writes = false;
    bool require_approval = false;
    std::string system_prompt;
    std::string allowed_commands;
    std::int64_t context_budget_tokens = 0;
};
inline void append_value(std::string& out, const RunSettings& v) {
    out += "{";
    out += "\"model_dir\":";
    append_value(out, v.model_dir);
    out += ",";
    out += "\"workspace_root\":";
    append_value(out, v.workspace_root);
    out += ",";
    out += "\"mode\":";
    append_value(out, v.mode);
    out += ",";
    out += "\"sampling\":";
    append_value(out, v.sampling);
    out += ",";
    out += "\"max_iterations\":";
    append_value(out, v.max_iterations);
    out += ",";
    out += "\"wall_clock_seconds\":";
    append_value(out, v.wall_clock_seconds);
    out += ",";
    out += "\"sandbox_tier\":";
    append_value(out, v.sandbox_tier);
    out += ",";
    out += "\"auto_approve_exec\":";
    append_value(out, v.auto_approve_exec);
    out += ",";
    out += "\"auto_approve_writes\":";
    append_value(out, v.auto_approve_writes);
    out += ",";
    out += "\"require_approval\":";
    append_value(out, v.require_approval);
    out += ",";
    out += "\"system_prompt\":";
    append_value(out, v.system_prompt);
    out += ",";
    out += "\"allowed_commands\":";
    append_value(out, v.allowed_commands);
    out += ",";
    out += "\"context_budget_tokens\":";
    append_value(out, v.context_budget_tokens);
    out += "}";
}

struct CapabilityChips {
    bool writes_outside_workspace = false;
    bool reads_outside_workspace = false;
    bool destroys_data = false;
    bool rewrites_vcs_history = false;
    bool network_access = false;
    bool spawns_unbounded_process = false;
    bool signals_foreign_process = false;
    bool escalates_privileges = false;
    std::string parse_status;
};
inline void append_value(std::string& out, const CapabilityChips& v) {
    out += "{";
    out += "\"writes_outside_workspace\":";
    append_value(out, v.writes_outside_workspace);
    out += ",";
    out += "\"reads_outside_workspace\":";
    append_value(out, v.reads_outside_workspace);
    out += ",";
    out += "\"destroys_data\":";
    append_value(out, v.destroys_data);
    out += ",";
    out += "\"rewrites_vcs_history\":";
    append_value(out, v.rewrites_vcs_history);
    out += ",";
    out += "\"network_access\":";
    append_value(out, v.network_access);
    out += ",";
    out += "\"spawns_unbounded_process\":";
    append_value(out, v.spawns_unbounded_process);
    out += ",";
    out += "\"signals_foreign_process\":";
    append_value(out, v.signals_foreign_process);
    out += ",";
    out += "\"escalates_privileges\":";
    append_value(out, v.escalates_privileges);
    out += ",";
    out += "\"parse_status\":";
    append_value(out, v.parse_status);
    out += "}";
}

struct PerfSample {
    double ttft_ms = 0.0;
    double prefill_tok_per_s = 0.0;
    double decode_tok_per_s = 0.0;
    std::int64_t context_used = 0;
    std::int64_t context_max = 0;
    std::int64_t tokens_generated = 0;
};
inline void append_value(std::string& out, const PerfSample& v) {
    out += "{";
    out += "\"ttft_ms\":";
    append_value(out, v.ttft_ms);
    out += ",";
    out += "\"prefill_tok_per_s\":";
    append_value(out, v.prefill_tok_per_s);
    out += ",";
    out += "\"decode_tok_per_s\":";
    append_value(out, v.decode_tok_per_s);
    out += ",";
    out += "\"context_used\":";
    append_value(out, v.context_used);
    out += ",";
    out += "\"context_max\":";
    append_value(out, v.context_max);
    out += ",";
    out += "\"tokens_generated\":";
    append_value(out, v.tokens_generated);
    out += "}";
}

// request "lmp/start"
struct StartParams {
    std::string mission;
    RunSettings settings;
};
struct StartResult {
    std::string run_id;
};

// request "lmp/cancel"
struct CancelParams {
    std::string run_id;
};
struct CancelResult {
    bool accepted = false;
};

// request "lmp/approve"
struct ApproveParams {
    std::string request_id;
    bool approved = false;
};
struct ApproveResult {
    bool accepted = false;
};

// request "lmp/message"
struct MessageParams {
    std::string run_id;
    std::string text;
};
struct MessageResult {
    bool accepted = false;
    std::string run_id;
    bool started_run = false;
};

// request "lmp/shutdown"
struct ShutdownParams {
};
struct ShutdownResult {
    bool ok = false;
};

// notification "lmp/token"
struct TokenNotification {
    std::string run_id;
    std::string text;
    std::string channel;
    static constexpr const char* kMethod = "lmp/token";
};
[[nodiscard]] inline std::string to_json(const TokenNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"text\":";
    append_value(out, n.text);
    out += ",";
    out += "\"channel\":";
    append_value(out, n.channel);
    out += "}";
    return out;
}

// notification "lmp/turn"
struct TurnNotification {
    std::string run_id;
    std::string outcome;
    std::string tool_name;
    std::string tool_args;
    std::string tool_status;
    std::string summary;
    double duration_ms = 0.0;
    static constexpr const char* kMethod = "lmp/turn";
};
[[nodiscard]] inline std::string to_json(const TurnNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"outcome\":";
    append_value(out, n.outcome);
    out += ",";
    out += "\"tool_name\":";
    append_value(out, n.tool_name);
    out += ",";
    out += "\"tool_args\":";
    append_value(out, n.tool_args);
    out += ",";
    out += "\"tool_status\":";
    append_value(out, n.tool_status);
    out += ",";
    out += "\"summary\":";
    append_value(out, n.summary);
    out += ",";
    out += "\"duration_ms\":";
    append_value(out, n.duration_ms);
    out += "}";
    return out;
}

// notification "lmp/checklist"
struct ChecklistNotification {
    std::string run_id;
    std::string items_json;
    static constexpr const char* kMethod = "lmp/checklist";
};
[[nodiscard]] inline std::string to_json(const ChecklistNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"items_json\":";
    append_value(out, n.items_json);
    out += "}";
    return out;
}

// notification "lmp/verification"
struct VerificationNotification {
    std::string run_id;
    std::string contract;
    bool passed = false;
    bool falsifiable = false;
    std::string detail;
    static constexpr const char* kMethod = "lmp/verification";
};
[[nodiscard]] inline std::string to_json(const VerificationNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"contract\":";
    append_value(out, n.contract);
    out += ",";
    out += "\"passed\":";
    append_value(out, n.passed);
    out += ",";
    out += "\"falsifiable\":";
    append_value(out, n.falsifiable);
    out += ",";
    out += "\"detail\":";
    append_value(out, n.detail);
    out += "}";
    return out;
}

// notification "lmp/approval_request"
struct ApprovalRequestNotification {
    std::string request_id;
    std::string run_id;
    std::string tool_name;
    std::string preview;
    std::string command;
    bool irreversible = false;
    double risk = 0.0;
    CapabilityChips capabilities;
    static constexpr const char* kMethod = "lmp/approval_request";
};
[[nodiscard]] inline std::string to_json(const ApprovalRequestNotification& n) {
    std::string out = "{";
    out += "\"request_id\":";
    append_value(out, n.request_id);
    out += ",";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"tool_name\":";
    append_value(out, n.tool_name);
    out += ",";
    out += "\"preview\":";
    append_value(out, n.preview);
    out += ",";
    out += "\"command\":";
    append_value(out, n.command);
    out += ",";
    out += "\"irreversible\":";
    append_value(out, n.irreversible);
    out += ",";
    out += "\"risk\":";
    append_value(out, n.risk);
    out += ",";
    out += "\"capabilities\":";
    append_value(out, n.capabilities);
    out += "}";
    return out;
}

// notification "lmp/edit"
struct EditNotification {
    std::string run_id;
    std::string path;
    std::string new_content;
    static constexpr const char* kMethod = "lmp/edit";
};
[[nodiscard]] inline std::string to_json(const EditNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"path\":";
    append_value(out, n.path);
    out += ",";
    out += "\"new_content\":";
    append_value(out, n.new_content);
    out += "}";
    return out;
}

// notification "lmp/perf"
struct PerfNotification {
    std::string run_id;
    PerfSample sample;
    static constexpr const char* kMethod = "lmp/perf";
};
[[nodiscard]] inline std::string to_json(const PerfNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"sample\":";
    append_value(out, n.sample);
    out += "}";
    return out;
}

// notification "lmp/run_end"
struct RunEndNotification {
    std::string run_id;
    std::string termination_reason;
    std::int64_t iterations = 0;
    bool completed = false;
    std::int64_t unfinished_items = 0;
    static constexpr const char* kMethod = "lmp/run_end";
};
[[nodiscard]] inline std::string to_json(const RunEndNotification& n) {
    std::string out = "{";
    out += "\"run_id\":";
    append_value(out, n.run_id);
    out += ",";
    out += "\"termination_reason\":";
    append_value(out, n.termination_reason);
    out += ",";
    out += "\"iterations\":";
    append_value(out, n.iterations);
    out += ",";
    out += "\"completed\":";
    append_value(out, n.completed);
    out += ",";
    out += "\"unfinished_items\":";
    append_value(out, n.unfinished_items);
    out += "}";
    return out;
}

} // namespace lmp::protocol
