#!/usr/bin/env python3
"""Generates the protocol types for BOTH sides from protocol/schema.json (spec S4.4).

  ./scripts/gen_protocol.py --root .          # write the generated files
  ./scripts/gen_protocol.py --root . --check  # regenerate to memory and diff

Hand-mirrored protocols drift silently, and the drift shows up as a field that is
always its default value on one side. Here the schema is the source and both
sides are outputs, so a field that exists on one side only cannot be expressed.
The --check mode is the protocol ratchet; it fails on any difference.
"""

import argparse
import json
import os
import sys

CPP_TYPES = {"string": "std::string", "int": "std::int64_t", "double": "double",
             "bool": "bool"}
TS_TYPES = {"string": "string", "int": "number", "double": "number", "bool": "boolean"}
CPP_DEFAULT = {"string": "", "int": " = 0", "double": " = 0.0", "bool": " = false"}

BANNER = ("// GENERATED by scripts/gen_protocol.py from protocol/schema.json.\n"
          "// Do not edit. The protocol ratchet regenerates and diffs this file, so an\n"
          "// edit here fails the build rather than drifting silently (S4.4).\n")


def method_ident(method):
    return method.split("/", 1)[1]


def cpp_field(field, structs):
    t = field["type"]
    if t in CPP_TYPES:
        return f"    {CPP_TYPES[t]} {field['name']}{CPP_DEFAULT[t]};"
    if t in structs:
        return f"    {t} {field['name']};"
    return f"    std::string {field['name']};"  # enums cross the wire as strings


def ts_field(field, structs, enums):
    t = field["type"]
    if t in TS_TYPES:
        return f"  {field['name']}: {TS_TYPES[t]};"
    if t in enums:
        return f"  {field['name']}: {t};"
    return f"  {field['name']}: {t};"


def gen_cpp(schema):
    structs, enums = schema["structs"], schema["enums"]
    out = [BANNER, "#pragma once\n", "#include <cstdint>", "#include <string>",
           "#include <vector>\n", "namespace lmp::protocol {\n"]
    out.append(f'inline constexpr const char* kProtocolVersion = "{schema["version"]}";\n')
    out.append("""// Value serializers. String escaping is delegated to the platform layer so the
// protocol and the event log cannot disagree about what a JSON string is.
void append_value(std::string& out, const std::string& v);
inline void append_value(std::string& out, std::int64_t v) { out += std::to_string(v); }
inline void append_value(std::string& out, double v) { out += std::to_string(v); }
inline void append_value(std::string& out, bool v) { out += v ? "true" : "false"; }
""")

    for name, values in enums.items():
        out.append(f"// {name}: crosses the wire as one of these literals.")
        out.append(f"namespace {name.lower()}_values {{")
        for v in values:
            out.append(f'inline constexpr const char* k{v.title().replace("_", "")} = "{v}";')
        out.append("}\n")

    for name, fields in structs.items():
        out.append(f"struct {name} {{")
        out.extend(cpp_field(f, structs) for f in fields)
        out.append("};")
        out.append(f"inline void append_value(std::string& out, const {name}& v) {{")
        out.append('    out += "{";')
        for i, f in enumerate(fields):
            sep = "" if i == 0 else '    out += ",";\n'
            out.append(f'{sep}    out += "\\"{f["name"]}\\":";')
            out.append(f"    append_value(out, v.{f['name']});")
        out.append('    out += "}";')
        out.append("}\n")

    for method, spec in schema["requests"].items():
        ident = method_ident(method).title().replace("_", "")
        out.append(f'// request "{method}"')
        out.append(f"struct {ident}Params {{")
        out.extend(cpp_field(f, structs) for f in spec["params"])
        out.append("};")
        out.append(f"struct {ident}Result {{")
        out.extend(cpp_field(f, structs) for f in spec["result"])
        out.append("};\n")

    for method, fields in schema["notifications"].items():
        ident = method_ident(method).title().replace("_", "")
        out.append(f'// notification "{method}"')
        out.append(f"struct {ident}Notification {{")
        out.extend(cpp_field(f, structs) for f in fields)
        out.append(f'    static constexpr const char* kMethod = "{method}";')
        out.append("};")
        out.append(f"[[nodiscard]] inline std::string to_json(const {ident}Notification& n) {{")
        out.append('    std::string out = "{";')
        for i, f in enumerate(fields):
            sep = "" if i == 0 else '    out += ",";\n'
            out.append(f'{sep}    out += "\\"{f["name"]}\\":";')
            out.append(f"    append_value(out, n.{f['name']});")
        out.append('    out += "}";')
        out.append("    return out;")
        out.append("}\n")

    out.append("} // namespace lmp::protocol")
    return "\n".join(out) + "\n"


def gen_ts(schema):
    structs, enums = schema["structs"], schema["enums"]
    out = [BANNER.replace("//", "//"), ""]
    out.append(f'export const PROTOCOL_VERSION = "{schema["version"]}";\n')
    for name, values in enums.items():
        union = " | ".join(f'"{v}"' for v in values)
        out.append(f"export type {name} = {union};")
    out.append("")
    for name, fields in structs.items():
        out.append(f"export interface {name} {{")
        out.extend(ts_field(f, structs, enums) for f in fields)
        out.append("}\n")
    for method, spec in schema["requests"].items():
        ident = method_ident(method).title().replace("_", "")
        out.append(f"export interface {ident}Params {{")
        out.extend(ts_field(f, structs, enums) for f in spec["params"])
        out.append("}")
        out.append(f"export interface {ident}Result {{")
        out.extend(ts_field(f, structs, enums) for f in spec["result"])
        out.append("}\n")
    for method, fields in schema["notifications"].items():
        ident = method_ident(method).title().replace("_", "")
        out.append(f"export interface {ident}Notification {{")
        out.extend(ts_field(f, structs, enums) for f in fields)
        out.append("}\n")
    methods = list(schema["requests"]) + list(schema["notifications"])
    out.append("export const METHODS = [")
    out.extend(f'  "{m}",' for m in methods)
    out.append("] as const;")
    return "\n".join(out) + "\n"


TARGETS = [("src/surface/protocol_generated.hpp", gen_cpp),
           ("extension/src/protocol.generated.ts", gen_ts)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    root = os.path.abspath(args.root)
    with open(os.path.join(root, "protocol", "schema.json"), encoding="utf-8") as fh:
        schema = json.load(fh)

    drift = False
    for rel, gen in TARGETS:
        path = os.path.join(root, rel)
        want = gen(schema)
        if args.check:
            have = ""
            if os.path.exists(path):
                with open(path, encoding="utf-8") as fh:
                    have = fh.read()
            if have != want:
                print(f"DRIFT {rel}: generated output differs from what is checked in")
                drift = True
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(want)
        print(f"wrote {rel}")
    if args.check and not drift:
        print(f"protocol: {len(TARGETS)} generated file(s) match the schema")
    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
